#!/bin/bash
echo "            _____ _______    _____ _    _ _____ _______ 
     /\    / ____|__   __|  / ____| |  | |_   _|__   __|
    /  \  | (___    | |    | (___ | |  | | | |    | |   
   / /\ \  \___ \   | |     \___ \| |  | | | |    | |   
  / ____ \ ____) |  | |     ____) | |__| |_| |_   | |   
 /_/    \_\_____/   |_|    |_____/ \____/|_____|  |_|   
                                                        
                                                        "
echo "Starting experiment: $1"

# start load generator
tmux new-window -n loadgen "cd workload-generator && python3 request_generator.py"